config/routes.rb
TravelShow::Application.routes.draw do
  resources :experiences

  resources :blobstores

  resources :data

  resources :posts

  resources :pictures

  resources :firstdaylasttravels

    
    resources :travels do
        collection do
            get 'add_experience_partial'
        end
    end

  resources :days
  
    resources :pictures

  get "home/index"
  resources :friends

resources :users

get "days/index"
    resources :days

    
get "travels/index"

    
get "pictures/index"
    resources :pictures
    
get "posts/index"
    resources :posts
    
get "data_files/index"
    resources :data_files
    
get "blobstores/index"
    resources :blobstores
    

    

   root 'home#index'

  

  

end

app/models/blobstore.rb
class Blobstore < ActiveRecord::Base
    
    has_attached_file :picture
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
    def self.save(upload)
        name = upload['datafile'].original_filename
        #contentType = upload['datafile'].content_type
        directory = "public/data"
        path = File.join(directory , name)
        File.open(path , "wb") { |f| f.write(upload['datafile'].read) }
    end
end

app/models/datum.rb
class Datum < ActiveRecord::Base
    def self.save(upload)
        name = upload['data'].original_filename
        #contentType = upload['data'].content_type
        directory = "public/data"
        path = File.join(directory , name)
        File.open(path , "wb") { |f| f.write(upload['data'].read) }
end
end

app/models/day.rb
class Day < ActiveRecord::Base
end

app/models/experience.rb
class Experience < ActiveRecord::Base
    
    belongs_to :travel
    validates_presence_of :title
    
    has_attached_file :picture
end

app/models/firstdaylasttravel.rb
class Firstdaylasttravel < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
    belongs_to :user
    has_many :travels
    
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :travel
end

app/models/travel.rb
class Travel < ActiveRecord::Base
    belongs_to :friend
    has_many :posts
    has_many :experiences
    
    has_attached_file :photo
    
    accepts_nested_attributes_for :experiences
    validates_presence_of :title
    
    #def new_experience_attributes=(experience_attributes)
    #experience_attributes.each do |attr|
    #experiences.build(attr)
    #end
    #end

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :friends
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render action: 'show', status: :created, location: @friend }
      else
        format.html { render action: 'new' }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|z
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:user_name, :friend_user_name, :active, :active_since, :created_at, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def link_to_add_fields(name, f, association)
        new_object = f.object.class.reflect_on_association(association).klass.new
        fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
            render(association.to_s.singularize + "_fields", :f => builder)
        end
        link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
    end
    
end

app/helpers/blobstores_helper.rb
module BlobstoresHelper

    
end

app/helpers/data_file_helper.rb
module DataFileHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    
end

app/helpers/home_helper.rb
module HomeHelper
    
    
    
    def initializeData(user_id)
        @user = User.where(user_name: user_id).first
        @currentFriends = @user.friends
        @firstFriend = @user.friends.first
        @firstTravel = @firstFriend.travels.first
    end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
    
    def getfriendId(userName)
        @meFriend = Friend.where(user_name: userName).first
        @user_id = @meFriend.user_id
    end
    
    def add_experience_link(name)
        link_to_function name, "" do |page|
            page.insert_html :bottom, :experiences, :partial => 'experience', :object => Experience.new
        end
    
    end
    

    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :friend_user_name %><br>
    <%= f.text_field :friend_user_name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.number_field :active %>
  </div>
  <div class="field">
    <%= f.label :active_since %><br>
    <%= f.date_select :active_since %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.date_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
<div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<h1>Listing friends</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Friend user name</th>
      <th>Active</th>
      <th>Active since</th>
      <th>Created at</th>
      <th>Image</th>
      <th>User_Id</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.user_name %></td>
        <td><%= friend.friend_user_name %></td>
        <td><%= friend.active %></td>
        <td><%= friend.active_since %></td>
        <td><%= friend.created_at %></td>
        <td><%= friend.image %></td>
	<td><%= friend.user_id %></td>

        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @friend.user_name %>
</p>

<p>
  <strong>Friend user name:</strong>
  <%= @friend.friend_user_name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @friend.active %>
</p>

<p>
  <strong>Active since:</strong>
  <%= @friend.active_since %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @friend.created_at %>
</p>

<p>
  <strong>Image:</strong>
  <%= @friend.image %>
</p>

<p>
  <strong>Image:</strong>
  <%= @friend.user_id %>
</p>


<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>