config/routes.rb
TravelShow::Application.routes.draw do
  resources :experiences

  resources :blobstores

  resources :data

  resources :posts

  resources :pictures

  resources :firstdaylasttravels

    
    resources :travels do
        collection do
            get 'add_experience_partial'
        end
    end

  resources :days
  
    resources :pictures

  get "home/index"
  resources :friends

resources :users

get "days/index"
    resources :days

    
get "travels/index"

    
get "pictures/index"
    resources :pictures
    
get "posts/index"
    resources :posts
    
get "data_files/index"
    resources :data_files
    
get "blobstores/index"
    resources :blobstores
    

    

   root 'home#index'

  

  

end

app/models/blobstore.rb
class Blobstore < ActiveRecord::Base
    
    has_attached_file :picture
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
    def self.save(upload)
        name = upload['datafile'].original_filename
        #contentType = upload['datafile'].content_type
        directory = "public/data"
        path = File.join(directory , name)
        File.open(path , "wb") { |f| f.write(upload['datafile'].read) }
    end
end

app/models/datum.rb
class Datum < ActiveRecord::Base
    def self.save(upload)
        name = upload['data'].original_filename
        #contentType = upload['data'].content_type
        directory = "public/data"
        path = File.join(directory , name)
        File.open(path , "wb") { |f| f.write(upload['data'].read) }
end
end

app/models/day.rb
class Day < ActiveRecord::Base
end

app/models/experience.rb
class Experience < ActiveRecord::Base
    
    belongs_to :travel
    validates_presence_of :title
    
    has_attached_file :picture
end

app/models/firstdaylasttravel.rb
class Firstdaylasttravel < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
    belongs_to :user
    has_many :travels
    
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :travel
end

app/models/travel.rb
class Travel < ActiveRecord::Base
    belongs_to :friend
    has_many :posts
    has_many :experiences
    
    has_attached_file :photo
    
    accepts_nested_attributes_for :experiences
    validates_presence_of :title
    
    #def new_experience_attributes=(experience_attributes)
    #experience_attributes.each do |attr|
    #experiences.build(attr)
    #end
    #end

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :friends
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
    @experience.travel_id = @@lastTravel.id
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render action: 'show', status: :created, location: @experience }
      else
        format.html { render action: 'new' }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
        params.require(:experience).permit(:title, :continent, :country, :city, :area, :recommended, :picture)
    end

end

app/helpers/blobstores_helper.rb
module BlobstoresHelper

    
end

app/helpers/data_file_helper.rb
module DataFileHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    
end

app/helpers/home_helper.rb
module HomeHelper
    
    
    
    def initializeData(user_id)
        @user = User.where(user_name: user_id).first
        @currentFriends = @user.friends
        @firstFriend = @user.friends.first
        @firstTravel = @firstFriend.travels.first
    end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
    
    def getfriendId(userName)
        @meFriend = Friend.where(user_name: userName).first
        @user_id = @meFriend.user_id
    end
    
    def add_experience_link(name)
        link_to_function name, "" do |page|
            page.insert_html :bottom, :experiences, :partial => 'experience', :object => Experience.new
        end
    
    end
    

    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>







<form class="form-horizontal">

	<div class="container-fluid well">

		<div class="span6">
			<div class="row-fluid">
	  			<div class="control-group">   
            			    <div class="controls" id="divImage">  
					<%=f.file_field :picture %>

					<% if params[:action] != 'new'%>
						<%=image_tag( @experience.picture.url, id: "edit_front_page_image", alt: "Icon", size: "200x200") %> 
				        	<img class="imgEdit" id="opacityEditImage" src="http://placehold.it/150x150" style="display:none"></img>
					<%end%>					
            			    </div>  
          			</div>  
			</div>
		</div>
		<div style="display: none;">
			<%= f.text_field :travel_id, :value => @experience.travel_id %>
		</div>

 
		<div class="span6"> 
  			<div class="row-fluid"> 
        			<fieldset>  
          				<div class="control-group">  
            					<label class="control-label" for="input01"><%= f.label :title %></label>  
            				    <div class="controls">  
              					<%= f.text_field :title %>   
            				    </div>  
          				</div>  
          				<div class="control-group">  
            				       <label class="control-label" for="input01"><%= f.label :continent %></label>  
            				   <div class="controls">  
              				       <%= f.text_field :continent %>  
            				   </div>  
          				</div> 
					<div class="control-group">  
            				       <label class="control-label" for="input01"><%= f.label :country %></label>  
            				   <div class="controls">  
              				       <%= f.text_field :country %>  
            				   </div>  
          				</div>  

					<div class="control-group">  
            				       <label class="control-label" for="input01"><%= f.label :city %></label>  
            				   <div class="controls">  
              				       <%= f.text_field :city %>  
            				   </div>  
          				</div> 

					<div class="control-group">  
            				       <label class="control-label" for="input01"><%= f.label :area %></label>  
            				   <div class="controls">  
              				       <%= f.text_field :area %>  
            				   </div>  
          				</div> 

					<div class="control-group">  
            				       <label class="control-label" for="input01"><%= f.label :recommended%></label>  
            				   <div class="controls">  
              				       <%= f.text_field :recommended %>  
            				   </div>  
          				</div> 
 
          				<div class="control-group">  
            					<label class="control-label" for="optionsCheckbox" reado>Checkbox (disabled)</label>  
            				    <div class="controls">  
              					<label class="checkbox">  
                				<input type="checkbox" id="optionsCheckbox" value="<%=@user_id%>" disabled></input>  
            				   </div>  
          				</div>  
          				<div class="form-actions">  
            					<button type="submit" class="btn btn-primary">Save changes</button>  
            					<button class="btn">Cancel</button>  
          				</div>  
        			</fieldset>
			</div>
		</div> 

	</div>   
</form>

 <% end %>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<h1>Listing experiences</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Continent</th>
      <th>Country</th>
      <th>City</th>
      <th>Area</th>
      <th>Recommended</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.title %></td>
        <td><%= experience.continent %></td>
        <td><%= experience.country %></td>
        <td><%= experience.city %></td>
        <td><%= experience.area %></td>
        <td><%= experience.recommended %></td>
        <td><%= link_to 'Show', experience %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<legend>New Experience</legend>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @experience.title %>
</p>

<p>
  <strong>Continent:</strong>
  <%= @experience.continent %>
</p>

<p>
  <strong>Country:</strong>
  <%= @experience.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @experience.city %>
</p>

<p>
  <strong>Area:</strong>
  <%= @experience.area %>
</p>

<p>
  <strong>Recommended:</strong>
  <%= @experience.recommended %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>