config/routes.rb
TravelShow::Application.routes.draw do
  resources :experiences

  resources :blobstores

  resources :data

  resources :posts

  resources :pictures

  resources :firstdaylasttravels

    
    resources :travels do
        collection do
            get 'add_experience_partial'
        end
    end

  resources :days
  
    resources :pictures

  get "home/index"
  resources :friends

resources :users

get "days/index"
    resources :days

    
get "travels/index"

    
get "pictures/index"
    resources :pictures
    
get "posts/index"
    resources :posts
    
get "data_files/index"
    resources :data_files
    
get "blobstores/index"
    resources :blobstores
    

    

   root 'home#index'

  

  

end

app/models/blobstore.rb
class Blobstore < ActiveRecord::Base
    
    has_attached_file :picture
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
    def self.save(upload)
        name = upload['datafile'].original_filename
        #contentType = upload['datafile'].content_type
        directory = "public/data"
        path = File.join(directory , name)
        File.open(path , "wb") { |f| f.write(upload['datafile'].read) }
    end
end

app/models/datum.rb
class Datum < ActiveRecord::Base
    def self.save(upload)
        name = upload['data'].original_filename
        #contentType = upload['data'].content_type
        directory = "public/data"
        path = File.join(directory , name)
        File.open(path , "wb") { |f| f.write(upload['data'].read) }
end
end

app/models/day.rb
class Day < ActiveRecord::Base
end

app/models/experience.rb
class Experience < ActiveRecord::Base
    
    belongs_to :travel
    validates_presence_of :title
    
    has_attached_file :picture
end

app/models/firstdaylasttravel.rb
class Firstdaylasttravel < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
    belongs_to :user
    has_many :travels
    
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :travel
end

app/models/travel.rb
class Travel < ActiveRecord::Base
    belongs_to :friend
    has_many :posts
    has_many :experiences
    
    has_attached_file :photo
    
    accepts_nested_attributes_for :experiences
    validates_presence_of :title
    
    #def new_experience_attributes=(experience_attributes)
    #experience_attributes.each do |attr|
    #experiences.build(attr)
    #end
    #end

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :friends
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:travel_id, :title, :country, :area, :hotel, :car, :comment, :created_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def link_to_add_fields(name, f, association)
        new_object = f.object.class.reflect_on_association(association).klass.new
        fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
            render(association.to_s.singularize + "_fields", :f => builder)
        end
        link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
    end
    
end

app/helpers/blobstores_helper.rb
module BlobstoresHelper

    
end

app/helpers/data_file_helper.rb
module DataFileHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    
end

app/helpers/home_helper.rb
module HomeHelper
    
    
    
    def initializeData(user_id)
        @user = User.where(user_name: user_id).first
        @currentFriends = @user.friends
        @firstFriend = @user.friends.first
        @firstTravel = @firstFriend.travels.first
    end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
    
    def getfriendId(userName)
        @meFriend = Friend.where(user_name: userName).first
        @user_id = @meFriend.user_id
    end
    
    def add_experience_link(name)
        link_to_function name, "" do |page|
            page.insert_html :bottom, :experiences, :partial => 'experience', :object => Experience.new
        end
    
    end
    

    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :travel_id %><br>
    <%= f.text_field :travel_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :hotel %><br>
    <%= f.text_field :hotel %>
  </div>
  <div class="field">
    <%= f.label :car %><br>
    <%= f.text_field :car %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.date_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <thead>
    <tr>
      <th>Travel</th>
      <th>Title</th>
      <th>Country</th>
      <th>Area</th>
      <th>Hotel</th>
      <th>Car</th>
      <th>Comment</th>
      <th>Created at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.travel_id %></td>
        <td><%= day.title %></td>
        <td><%= day.country %></td>
        <td><%= day.area %></td>
        <td><%= day.hotel %></td>
        <td><%= day.car %></td>
        <td><%= day.comment %></td>
        <td><%= day.created_at %></td>
        <td><%= link_to 'Show', day %></td>
        <td><%= link_to 'Edit', edit_day_path(day) %></td>
        <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Day', new_day_path %>

<br>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
        

<style type="text/css">
div.colorR {
  border-right-width:1px;
  border-right-style:ridge;
  border-right-color:#C0C0C0
  }
</style>


<div class="well">

	<div class="row-fluid">  
            <div class="span4 colorR">
                <h4>Country/Area</h4>
                <small>Today we are traveling in  <%= @day.country %> in an area called  <%= @day.area %>
                </small>
            </div>      
	    <div class="span4 colorR">
                <h5>Hotel</h5>
               <small>Today we are planning to stay in the  <%= @day.hotel %> hotel</small>
            </div>
            <div class="span4">
                <h5>Rental</h5>
                <small>Today we have rented a car from   <%= @day.car %></small> 
            </div>
	</div> 
</div>


<!--
<h5>
  <strong>Travel:</strong>
  <%= @day.travel_id %>
</h5>

 <p>
  <strong>Title:</strong>
  <%= @day.title %>

<p>
  <strong>Country:</strong>
  <%= @day.country %>
</p>


<p>
  <strong>Area:</strong>
  <%= @day.area %>
</p>
</p>
<p>
  <strong>Hotel:</strong>
  <%= @day.hotel %>
</p> 

<p>
  <strong>Car:</strong>
  <%= @day.car %>
</p>



<p>
  <strong>Comment:</strong>
  <%= @day.comment %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @day.created_at %>
</p>


</div>
</div>
</div>


<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %> -->