config/routes.rb
TravelShow::Application.routes.draw do
  resources :experiences

  resources :blobstores

  resources :data

  resources :posts

  resources :pictures

  resources :firstdaylasttravels

    
    resources :travels do
        collection do
            get 'add_experience_partial'
        end
    end

  resources :days
  
    resources :pictures

  get "home/index"
  resources :friends

resources :users

get "days/index"
    resources :days

    
get "travels/index"

    
get "pictures/index"
    resources :pictures
    
get "posts/index"
    resources :posts
    
get "data_files/index"
    resources :data_files
    
get "blobstores/index"
    resources :blobstores
    

    

   root 'home#index'

  

  

end

app/models/blobstore.rb
class Blobstore < ActiveRecord::Base
    
    has_attached_file :picture
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
    def self.save(upload)
        name = upload['datafile'].original_filename
        #contentType = upload['datafile'].content_type
        directory = "public/data"
        path = File.join(directory , name)
        File.open(path , "wb") { |f| f.write(upload['datafile'].read) }
    end
end

app/models/datum.rb
class Datum < ActiveRecord::Base
    def self.save(upload)
        name = upload['data'].original_filename
        #contentType = upload['data'].content_type
        directory = "public/data"
        path = File.join(directory , name)
        File.open(path , "wb") { |f| f.write(upload['data'].read) }
end
end

app/models/day.rb
class Day < ActiveRecord::Base
end

app/models/experience.rb
class Experience < ActiveRecord::Base
    
    belongs_to :travel
    validates_presence_of :title
    
    has_attached_file :picture
end

app/models/firstdaylasttravel.rb
class Firstdaylasttravel < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
    belongs_to :user
    has_many :travels
    
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :travel
end

app/models/travel.rb
class Travel < ActiveRecord::Base
    belongs_to :friend
    has_many :posts
    has_many :experiences
    
    has_attached_file :photo
    
    accepts_nested_attributes_for :experiences
    validates_presence_of :title
    
    #def new_experience_attributes=(experience_attributes)
    #experience_attributes.each do |attr|
    #experiences.build(attr)
    #end
    #end

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :friends
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:travel_id, :String, :image_url, :day_id, :String)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def link_to_add_fields(name, f, association)
        new_object = f.object.class.reflect_on_association(association).klass.new
        fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
            render(association.to_s.singularize + "_fields", :f => builder)
        end
        link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
    end
    
end

app/helpers/blobstores_helper.rb
module BlobstoresHelper

    
end

app/helpers/data_file_helper.rb
module DataFileHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    
end

app/helpers/home_helper.rb
module HomeHelper
    
    
    
    def initializeData(user_id)
        @user = User.where(user_name: user_id).first
        @currentFriends = @user.friends
        @firstFriend = @user.friends.first
        @firstTravel = @firstFriend.travels.first
    end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
    
    def getfriendId(userName)
        @meFriend = Friend.where(user_name: userName).first
        @user_id = @meFriend.user_id
    end
    
    def add_experience_link(name)
        link_to_function name, "" do |page|
            page.insert_html :bottom, :experiences, :partial => 'experience', :object => Experience.new
        end
    
    end
    

    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :travel_id %><br>
    <%= f.text_field :travel_id %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :day_id %><br>
    <%= f.text_field :day_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Travel</th>
      <th>Image url</th>
      <th>Day</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.travel_id %></td>
        <td><%= picture.image_url %></td>
        <td><%= picture.day_id %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
 <div class="row-fluid">
<!-- TODO add a span 12 row and split images -->
			<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>		
			</div> 
		 	<div class="span1">
	     		 <a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 
		 	<div class="span1">
	      		<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
             		</div>
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
             		</div>
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
             		</div>
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 
</div>
 <div class="row-fluid">
<!-- TODO add a span 12 row and split images -->
			<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>		
			</div> 
		 	<div class="span1">
	     		 <a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 
		 	<div class="span1">
	      		<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
             		</div>
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
             		</div>
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
             		</div>
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 
		 	<div class="span1">
	      			<a href="#"><%=image_tag("Bruce.jpg", id: "bruce", alt: "Icon", size: "50x45") %></a>	
			</div> 

</div>